# Generated by Django 5.0.7 on 2024-07-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playpulse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funfact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
    ]
